version: "3.7"

services:
    # sonarr
    Sonarr:
        container_name: Sonarr
        restart: unless-stopped
        image: cr.hotio.dev/hotio/sonarr
        ports:
            - "8989:8989"
        volumes:
            - /data/config/sonarr:/config
            - /data:/data
        environment:
            - PUID=1111
            - PGID=1002
            - UMASK=002
            - TZ=Australia/Brisbane

    # radarr
    Radarr:
        container_name: radarr
        restart: unless-stopped
        image: cr.hotio.dev/hotio/radarr
        ports: 
            - "7878:7878"
        volumes:
            - /data/config/radarr:/config
            - /data:/data
        environment:
            - PUID=1112
            - PGID=1002
            - UMASK=002
            - TZ=Australia/Brisbane

    # prowlarr
    Prowlarr:
        container_name: prowlarr
        restart: unless-stopped
        image: cr.hotio.dev/hotio/prowlarr
        ports:
            - "9696:9696"
        volumes:
            - /data/config/prowlarr:/config
        environment:
            - PUID=1113
            - PGID=1002
            - UMASK=002
            - TZ=Australia/Brisbane

    #jellyfin
    Jellyfin:
        container_name: jellyfin
        restart: unless-stopped
        image: cr.hotio.dev/hotio/jellyfin
        ports:
            - "8096:8096"
        volumes:
            - /data/config/jellyfin:/config
            - /data/media:/data/media
        environment:
            - PUID=1114
            - PGID=1002
            - UMASK=002
            - TZ=Australia/Brisbane

    #qbittorrent
    QBitTorrent:
        container_name: qbittorrent
        restart: unless-stopped
        image: cr.hotio.dev/hotio/qbittorrent
        ports: 
            - "8080:8080"
        volumes:
            - /data/config/qbittorrent:/config
            - /data/torrents:/data/torrents
        environment:
            - PUID=1115
            - PGID=1002
            - UMASK=002
            - TZ=Australia/Brisbane
